"use strict";var cspt_anchor_auto_scroll_link=function(){var offset=0;if(jQuery('.cspt-sticky-header.cspt-header-sticky-yes').length>0){offset=offset+jQuery('.cspt-sticky-header.cspt-header-sticky-yes').height()}
if(jQuery('#wpadminbar').length>0&&jQuery(window).width()>600){offset=offset+jQuery('#wpadminbar').height()}
if(window.location.hash){var hash=window.location.hash.substring(1);if(jQuery("#"+hash).length!=0){setTimeout(function(){jQuery('html, body').animate({scrollTop:jQuery('#'+hash).offset().top-offset},500)},100)}}}
var cspt_anchor_link=function(){var nav=jQuery('.mega-menu-wrap, .cspt-navbar > div, .cspt-header-sticky-yes .cspt-navbar > div');var offset=0;if(jQuery('.cspt-sticky-header.cspt-header-sticky-yes').length>0){offset=offset+jQuery('.cspt-sticky-header.cspt-header-sticky-yes').height()}
if(jQuery('#wpadminbar').length>0&&jQuery(window).width()>600){offset=offset+jQuery('#wpadminbar').height()}
nav.find('a').on('click',function(){var $el=jQuery(this),id=$el.attr('href');if(id.includes("#")){var arr=id.split('#')[1];if(jQuery("#"+arr).length!=0){window.history.pushState('page2','Title',id);jQuery(".cspt-navbar > div, body, .mega-menu-wrap").toggleClass("active");jQuery('html, body').animate({scrollTop:jQuery('#'+arr).offset().top-offset},500);return!1}}})}
var cspt_one_page_on_scroll=function(){if(jQuery('body').hasClass('cspt-one-page-site')){var offset=0;if(jQuery('.cspt-sticky-header.cspt-header-sticky-yes').length>0){offset=offset+jQuery('.cspt-sticky-header.cspt-header-sticky-yes').height()}
if(jQuery('#wpadminbar').length>0&&jQuery(window).width()>600){offset=offset+jQuery('#wpadminbar').height()}
var sections=jQuery('.elementor-top-section, section.wpb-content-wrapper > .cspt-row , .cspt-slider-area'),nav=jQuery('.mega-menu-wrap, .cspt-navbar > div'),nav_height=jQuery('.cspt-sticky-header').height();if(jQuery('body').scrollTop()<5){if(jQuery('body').hasClass('home')){nav.find('a').parent().removeClass('mega-current-menu-item mega-current_page_item current-menu-ancestor current-menu-item current_page_item');nav.find('a[href="#page"]').parent().addClass('mega-current-menu-item mega-current_page_item current-menu-ancestor current-menu-item current_page_item')}}
var cur_pos=jQuery(window).scrollTop();sections.each(function(){var top=jQuery(this).offset().top-(nav_height+2)-offset,bottom=top+jQuery(this).outerHeight()+offset;if(cur_pos>=top&&cur_pos<=bottom){if(typeof jQuery(this)!='undefined'&&typeof jQuery(this).attr('id')!='undefined'&&jQuery(this).attr('id')!=''){var mainThis=jQuery(this);nav.find('a').removeClass('mega-current-menu-item mega-current_page_item current-menu-ancestor current-menu-item current_page_item');jQuery(this).addClass('mega-current-menu-item mega-current_page_item current-menu-ancestor current-menu-item current_page_item');var arr=mainThis.attr('id');nav.find('a').parent().removeClass('mega-current-menu-item mega-current_page_item current-menu-ancestor current-menu-item current_page_item');nav.find('a').each(function(){var menuAttr=jQuery(this).attr('href').split('#')[1];if(menuAttr==arr){jQuery(this).parent().addClass('mega-current-menu-item mega-current_page_item current-menu-ancestor current-menu-item current_page_item')}})}}})}}
var cspt_sticky_header=function(){if(jQuery('.cspt-header-sticky-yes').length>0){var header_html=jQuery('#masthead .cspt-header-inner').html();jQuery('.cspt-sticky-header').append(header_html);jQuery('.cspt-sticky-header .main-navigation ul, .cspt-sticky-header .main-navigation ul li, .cspt-sticky-header .main-navigation ul li a').removeAttr('id');jQuery('.cspt-sticky-header h1').each(function(){var thisele=jQuery(this);var thisele_class=jQuery(this).attr('class');thisele.replaceWith('<span class="'+thisele_class+'">'+jQuery(thisele).html()+'</span>')});if(jQuery('.cspt-header-inner').hasClass('cspt-infostack-header')){jQuery(".cspt-sticky-header .cspt-header-menu").insertAfter(".cspt-sticky-header .site-branding");jQuery('.cspt-sticky-header .cspt-header-info, .cspt-sticky-header .cspt-mobile-search, .cspt-sticky-header .cspt-social-links , .cspt-header-style-4 .cspt-sticky-header .cspt-pre-header-wrapper ').remove()}}}
var cspt_sticky_header_class=function(){if(jQuery('#wpadminbar').length>0){jQuery('#masthead').addClass('cspt-adminbar-exists')}
var offset_px=40;if(jQuery('.cspt-header-inner').length>0){offset_px=jQuery('.cspt-header-inner').height()+offset_px}
if(jQuery(window).scrollTop()>offset_px){jQuery('#masthead').addClass('cspt-fixed-header');jQuery('.cspt-sticky-header .mega-menu.max-mega-menu.mega-menu-horizontal').attr("id","mega-menu-creativesplanet-top")}else{jQuery('#masthead').removeClass('cspt-fixed-header')}
jQuery(window).scroll(function(){if(jQuery(window).scrollTop()>offset_px){jQuery('#masthead').addClass('cspt-fixed-header');jQuery('.cspt-sticky-header .mega-menu.max-mega-menu.mega-menu-horizontal').attr("id","mega-menu-creativesplanet-top")}else{jQuery('#masthead').removeClass('cspt-fixed-header')}})}
var cspt_sorting=function(){jQuery('.cspt-sortable-yes').each(function(){var boxes=jQuery('.cspt-element-posts-wrapper',this);var links=jQuery('.cspt-sortable-list a',this);boxes.isotope({animationEngine:'best-available'});links.on('click',function(e){var selector=jQuery(this).data('sortby');if(selector!='*'){var selector='.'+selector}
boxes.isotope({filter:selector,itemSelector:'.cspt-ele',layoutMode:'fitRows'});links.removeClass('cspt-selected');jQuery(this).addClass('cspt-selected');e.preventDefault()})})}
var cspt_toggleSidebar=function(){jQuery('#menu-toggle').on('click',function(){jQuery("body:not(.mega-menu-creativesplanet-top) .cspt-navbar > div, body:not(.mega-menu-creativesplanet-top)").toggleClass("active")})
if(jQuery('.cspt-navbar > div > .closepanel').length==0){jQuery('.cspt-navbar > div').append('<span class="closepanel"><i class="cspt-base-icon-cancel"></i></span>');jQuery('.cspt-navbar > div > .closepanel, .mega-menu-creativesplanet-top .nav-menu-toggle').on('click',function(){jQuery(".cspt-navbar > div, body, .mega-menu-wrap").toggleClass("active")});if(jQuery('.cspt-header-inner .cspt-search-cart-box > .cspt-cart-wrapper').length>0){if(jQuery('.cspt-navbar > div > .cspt-responsive-icons').length==0){jQuery('.cspt-navbar > div').append("<div class='cspt-responsive-icons'></div>")}
jQuery('.cspt-navbar > div > .cspt-responsive-icons').append('<div class="cspt-cart-wrapper"></div>');jQuery('.cspt-navbar > div > .cspt-responsive-icons .cspt-cart-wrapper').append(jQuery('.cspt-header-inner .cspt-search-cart-box > .cspt-cart-wrapper').html())}
if(jQuery('.cspt-header-inner .cspt-search-cart-box > .cspt-header-search-btn').length>0){if(jQuery('.cspt-navbar > div > .cspt-responsive-icons').length==0){jQuery('.cspt-navbar > div').append("<div class='cspt-responsive-icons'></div>")}
jQuery('.cspt-navbar > div > .cspt-responsive-icons').append('<div class="cspt-header-search-btn"></div>');jQuery('.cspt-navbar > div > .cspt-responsive-icons .cspt-header-search-btn').append(jQuery('.cspt-header-inner .cspt-search-cart-box > .cspt-header-search-btn').html())}
return!1}}
var cspt_preloader=function(){jQuery(".cspt-preloader").fadeOut('600')}
var creativesplanet_stretched_col_calc=function(){if(jQuery('.wpb_column.cspt-col-stretched-yes').length>0){var window_width=jQuery(window).width();var document_width=jQuery(document).width();jQuery('.wpb_column.cspt-col-stretched-yes').each(function(){var this_ele=jQuery(this);var main_width=jQuery('#main').width();var extra_width=((window_width-main_width)/2);var curr_width=jQuery('.wpb_wrapper',this_ele).width();var wrapper_div='';var minimum_width=0;var both_margin=!1;if(this_ele.parent().hasClass('cspt-break-col-1200')){minimum_width=1200}else if(this_ele.parent().hasClass('cspt-break-col-991')){minimum_width=991}else if(this_ele.parent().hasClass('cspt-break-col-767')){minimum_width=767}
if(minimum_width>0&&document_width<minimum_width){both_margin=!0}
if(this_ele.hasClass('cspt-col-stretched-right')){if(this_ele.hasClass('cspt-col-stretched-content-yes')){wrapper_div=', .vc_column-inner > .wpb_wrapper'}
jQuery('.vc_column-inner > .cspt-stretched-div'+wrapper_div,this_ele).css('margin-right','-'+extra_width+'px');if(both_margin==!0){jQuery('.vc_column-inner > .cspt-stretched-div'+wrapper_div,this_ele).css('margin-left','-'+extra_width+'px')}else{jQuery('.vc_column-inner > .cspt-stretched-div'+wrapper_div,this_ele).css('margin-left','')}}else{if(this_ele.hasClass('cspt-col-stretched-content-yes')){wrapper_div=', .vc_column-inner > .wpb_wrapper'}
jQuery('.vc_column-inner > .cspt-stretched-div'+wrapper_div,this_ele).css('margin-left','-'+extra_width+'px');if(both_margin==!0){jQuery('.vc_column-inner > .cspt-stretched-div'+wrapper_div,this_ele).css('margin-right','-'+extra_width+'px')}else{jQuery('.vc_column-inner > .cspt-stretched-div'+wrapper_div,this_ele).css('margin-right','')}}})}}
jQuery(document).ready(function($){jQuery('.cspt-navbar li').on('hover',function(){if(jQuery(this).children("ul").length==1){var parent=jQuery(this);var child_menu=jQuery(this).children("ul");if(jQuery(parent).offset().left+jQuery(parent).width()+jQuery(child_menu).width()>jQuery(window).width()){jQuery(child_menu).addClass('cspt-nav-left')}else{jQuery(child_menu).removeClass('cspt-nav-left')}}});var i_type='image';jQuery('a.cspt-lightbox-video, .cspt-lightbox-video a, .cspt-lightbox a').each(function(){if(jQuery(this).hasClass('cspt-lightbox-video')||jQuery(this).closest('.wpb_single_image').hasClass('cspt-lightbox-video')||jQuery(this).closest('.elementor-element').hasClass('cspt-lightbox-video')||jQuery(this).closest('.vc_icon_element').hasClass('cspt-lightbox-video')){i_type='iframe'}else{i_type='image'}
jQuery(this).magnificPopup({type:i_type})});jQuery('.cspt-navbar > div > ul li:has(ul)').append("<span class='sub-menu-toggle'><i class='cspt-base-icon-down-open-big'></i></span>");jQuery('.cspt-popup').on('click',function(event){event.preventDefault();var href=jQuery(this).attr('href');var title=jQuery(this).attr('title');window.open(href,title,"width=600,height=500")});jQuery('.cspt-testimonial-active').each(function(){var ele_parent=jQuery(this).closest('.cspt-element-posts-wrapper');jQuery('.creativesplanet-ele.creativesplanet-ele-testimonial',ele_parent).on('mouseover',function(){jQuery('.creativesplanet-ele.creativesplanet-ele-testimonial',ele_parent).removeClass('cspt-testimonial-active');jQuery(this).addClass('cspt-testimonial-active')})});jQuery(function(){jQuery('.cspt-header-search-btn').on("click",function(event){event.preventDefault();jQuery(".cspt-header-search-form-wrapper").addClass("open");jQuery('.cspt-header-search-form-wrapper input[type="search"]').focus()});jQuery(".cspt-search-close").on("click keyup",function(event){jQuery(".cspt-header-search-form-wrapper").removeClass("open")})});jQuery(".nav-menu-toggle").on("click tap",function(){});jQuery('.sub-menu-toggle').on('click',function(){if(jQuery(this).siblings('.sub-menu, .children').hasClass('show')){jQuery(this).siblings('.sub-menu, .children').removeClass('show');jQuery('i',jQuery(this)).removeClass('cspt-base-icon-up-open-big').addClass('cspt-base-icon-down-open-big')}else{jQuery(this).siblings('.sub-menu, .children').addClass('show');jQuery('i',jQuery(this)).removeClass('cspt-base-icon-down-open-big').addClass('cspt-base-icon-up-open-big')}
return!1});var btn=jQuery('.scroll-to-top');jQuery(window).scroll(function(){if(jQuery(window).scrollTop()>300){btn.addClass('show')}else{btn.removeClass('show')}});btn.on('click',function(e){e.preventDefault();jQuery('html, body').animate({scrollTop:0},'300')})});var cspt_mousehover_tooltip=function(){jQuery("<div id='cspt-cursor'><div class='cspt-tooltip-content'></div></div>").appendTo("body");var cspt_text=jQuery('.cspt-element-portfolio-style-3 .creativesplanet-post-content');var cspt_cursor=jQuery("#cspt-cursor");jQuery(document).on('mousemove',function(e){var cspt_x=e.clientX;var cspt_y=e.clientY;cspt_cursor.css({"transform":"translate3d("+cspt_x+"px, "+cspt_y+"px, 0px)"})})
if(cspt_text.length){cspt_text.each(function(){var elm=jQuery(this);var cspt_html=elm.find('.cspt-tooltip').html();elm.on('mouseenter',function(){cspt_cursor.addClass('active').find('.cspt-tooltip-content').html(cspt_html)}).on('mouseleave',function(e){cspt_cursor.removeClass('active').find('.cspt-tooltip-content').html('')})})}}
var cspt_validate=function(){jQuery("#commentform").submit(function(event){var error=!1;jQuery('.cspt-form-error').hide();if(jQuery("#author").length>0&&!jQuery("#author").val()){jQuery('.comment-form-author .cspt-form-error').show();error=!0}
if(jQuery("#comment").length>0&&!jQuery("#comment").val()){jQuery('.comment-form-comment .cspt-form-error').show();error=!0}
if(jQuery("#email").length>0){if(!jQuery("#email").val()){jQuery('.comment-form-email .cspt-form-error.cspt-empty-email').show();error=!0}else{var valid_email=(/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(jQuery("#email").val()));if(valid_email!=!0){jQuery('.comment-form-email .cspt-form-error.cspt-invalid-email').show();error=!0}}}
if(error==!0){event.preventDefault();return!1}else{return!0}})}
jQuery(window).on('load',function(){jQuery('#vc_templates-more-layouts').off('click').on('click',function(){window.top.cspt_call_custom_template()});setTimeout(function(){cspt_anchor_auto_scroll_link()},500);cspt_one_page_on_scroll();cspt_anchor_link();cspt_preloader();cspt_sorting();jQuery("div.cspt-gallery").each(function(){jQuery(this).lightSlider({item:1,auto:!0,loop:!0,controls:!1,speed:1500,pause:5500})});cspt_mousehover_tooltip()});jQuery(document).ready(function(){cspt_validate();cspt_toggleSidebar();creativesplanet_stretched_col_calc();cspt_sticky_header_class();cspt_sticky_header();cspt_sorting()});jQuery(window).on('scroll',function(){cspt_one_page_on_scroll()})